package org.example.kurs_project;

import org.example.kurs_project.entity.*;
import org.example.kurs_project.service.ComponentService;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;

@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final ComponentService componentService;

    @Override
    public void run(String... args) {
        if (componentService.getAllComponents().isEmpty()) {
            Cpu cpu1 = new Cpu(); cpu1.setName("Core i5-12400F"); cpu1.setBrand("Intel"); cpu1.setPrice(new java.math.BigDecimal("14500")); cpu1.setSocket("LGA1700"); cpu1.setTdp(65); cpu1.setRamTypeSupport("DDR4, DDR5"); cpu1.setCores(6); componentService.saveComponent(cpu1);
            Cpu cpu2 = new Cpu(); cpu2.setName("Core i7-13700K"); cpu2.setBrand("Intel"); cpu2.setPrice(new java.math.BigDecimal("42000")); cpu2.setSocket("LGA1700"); cpu2.setTdp(253); cpu2.setRamTypeSupport("DDR4, DDR5"); cpu2.setCores(16); componentService.saveComponent(cpu2);
            Cpu cpu3 = new Cpu(); cpu3.setName("Ryzen 5 5600"); cpu3.setBrand("AMD"); cpu3.setPrice(new java.math.BigDecimal("12000")); cpu3.setSocket("AM4"); cpu3.setTdp(65); cpu3.setRamTypeSupport("DDR4"); cpu3.setCores(6); componentService.saveComponent(cpu3);
            Cpu cpu4 = new Cpu(); cpu4.setName("Ryzen 5 7500F"); cpu4.setBrand("AMD"); cpu4.setPrice(new java.math.BigDecimal("17000")); cpu4.setSocket("AM5"); cpu4.setTdp(65); cpu4.setRamTypeSupport("DDR5"); cpu4.setCores(6); componentService.saveComponent(cpu4);
            Cpu cpu5 = new Cpu(); cpu5.setName("Ryzen 7 7800X3D"); cpu5.setBrand("AMD"); cpu5.setPrice(new java.math.BigDecimal("38000")); cpu5.setSocket("AM5"); cpu5.setTdp(120); cpu5.setRamTypeSupport("DDR5"); cpu5.setCores(8); componentService.saveComponent(cpu5);
            Cpu cpu6 = new Cpu(); cpu6.setName("Core i3-12100F"); cpu6.setBrand("Intel"); cpu6.setPrice(new java.math.BigDecimal("8500")); cpu6.setSocket("LGA1700"); cpu6.setTdp(58); cpu6.setRamTypeSupport("DDR4, DDR5"); cpu6.setCores(4); componentService.saveComponent(cpu6);
            Cpu cpu7 = new Cpu(); cpu7.setName("Core i9-14900K"); cpu7.setBrand("Intel"); cpu7.setPrice(new java.math.BigDecimal("65000")); cpu7.setSocket("LGA1700"); cpu7.setTdp(253); cpu7.setRamTypeSupport("DDR4, DDR5"); cpu7.setCores(24); componentService.saveComponent(cpu7);
            Cpu cpu8 = new Cpu(); cpu8.setName("Core i5-14600KF"); cpu8.setBrand("Intel"); cpu8.setPrice(new java.math.BigDecimal("28000")); cpu8.setSocket("LGA1700"); cpu8.setTdp(181); cpu8.setRamTypeSupport("DDR4, DDR5"); cpu8.setCores(14); componentService.saveComponent(cpu8);
            Cpu cpu9 = new Cpu(); cpu9.setName("Ryzen 9 7950X3D"); cpu9.setBrand("AMD"); cpu9.setPrice(new java.math.BigDecimal("72000")); cpu9.setSocket("AM5"); cpu9.setTdp(120); cpu9.setRamTypeSupport("DDR5"); cpu9.setCores(16); componentService.saveComponent(cpu9);
            Cpu cpu10 = new Cpu(); cpu10.setName("Ryzen 5 8600G"); cpu10.setBrand("AMD"); cpu10.setPrice(new java.math.BigDecimal("22000")); cpu10.setSocket("AM5"); cpu10.setTdp(65); cpu10.setRamTypeSupport("DDR5"); cpu10.setCores(6); componentService.saveComponent(cpu10);
            Cpu cpu11 = new Cpu(); cpu11.setName("Ryzen 7 5700X"); cpu11.setBrand("AMD"); cpu11.setPrice(new java.math.BigDecimal("18000")); cpu11.setSocket("AM4"); cpu11.setTdp(65); cpu11.setRamTypeSupport("DDR4"); cpu11.setCores(8); componentService.saveComponent(cpu11);
            Cpu cpu12 = new Cpu(); cpu12.setName("Core i7-12700KF"); cpu12.setBrand("Intel"); cpu12.setPrice(new java.math.BigDecimal("32000")); cpu12.setSocket("LGA1700"); cpu12.setTdp(190); cpu12.setRamTypeSupport("DDR4, DDR5"); cpu12.setCores(12); componentService.saveComponent(cpu12);
            Cpu cpu13 = new Cpu(); cpu13.setName("Core i5-13400F"); cpu13.setBrand("Intel"); cpu13.setPrice(new java.math.BigDecimal("19000")); cpu13.setSocket("LGA1700"); cpu13.setTdp(148); cpu13.setRamTypeSupport("DDR4, DDR5"); cpu13.setCores(10); componentService.saveComponent(cpu13);
            Cpu cpu14 = new Cpu(); cpu14.setName("Core i9-13900KF"); cpu14.setBrand("Intel"); cpu14.setPrice(new java.math.BigDecimal("58000")); cpu14.setSocket("LGA1700"); cpu14.setTdp(253); cpu14.setRamTypeSupport("DDR4, DDR5"); cpu14.setCores(24); componentService.saveComponent(cpu14);
            Cpu cpu15 = new Cpu(); cpu15.setName("Core i7-14700K"); cpu15.setBrand("Intel"); cpu15.setPrice(new java.math.BigDecimal("48000")); cpu15.setSocket("LGA1700"); cpu15.setTdp(253); cpu15.setRamTypeSupport("DDR4, DDR5"); cpu15.setCores(20); componentService.saveComponent(cpu15);
            Cpu cpu16 = new Cpu(); cpu16.setName("Ryzen 5 7600X"); cpu16.setBrand("AMD"); cpu16.setPrice(new java.math.BigDecimal("22000")); cpu16.setSocket("AM5"); cpu16.setTdp(105); cpu16.setRamTypeSupport("DDR5"); cpu16.setCores(6); componentService.saveComponent(cpu16);
            Cpu cpu17 = new Cpu(); cpu17.setName("Ryzen 7 7700X"); cpu17.setBrand("AMD"); cpu17.setPrice(new java.math.BigDecimal("32000")); cpu17.setSocket("AM5"); cpu17.setTdp(105); cpu17.setRamTypeSupport("DDR5"); cpu17.setCores(8); componentService.saveComponent(cpu17);
            Cpu cpu18 = new Cpu(); cpu18.setName("Ryzen 9 7900X"); cpu18.setBrand("AMD"); cpu18.setPrice(new java.math.BigDecimal("52000")); cpu18.setSocket("AM5"); cpu18.setTdp(170); cpu18.setRamTypeSupport("DDR5"); cpu18.setCores(12); componentService.saveComponent(cpu18);
            Cpu cpu19 = new Cpu(); cpu19.setName("Ryzen 5 5500"); cpu19.setBrand("AMD"); cpu19.setPrice(new java.math.BigDecimal("9000")); cpu19.setSocket("AM4"); cpu19.setTdp(65); cpu19.setRamTypeSupport("DDR4"); cpu19.setCores(6); componentService.saveComponent(cpu19);
            Cpu cpu20 = new Cpu(); cpu20.setName("Ryzen 9 5950X"); cpu20.setBrand("AMD"); cpu20.setPrice(new java.math.BigDecimal("45000")); cpu20.setSocket("AM4"); cpu20.setTdp(105); cpu20.setRamTypeSupport("DDR4"); cpu20.setCores(16); componentService.saveComponent(cpu20);
            Cpu cpu21 = new Cpu(); cpu21.setName("Core i3-13100F"); cpu21.setBrand("Intel"); cpu21.setPrice(new java.math.BigDecimal("10000")); cpu21.setSocket("LGA1700"); cpu21.setTdp(58); cpu21.setRamTypeSupport("DDR4, DDR5"); cpu21.setCores(4); componentService.saveComponent(cpu21);
            Cpu cpu22 = new Cpu(); cpu22.setName("Core i5-12600K"); cpu22.setBrand("Intel"); cpu22.setPrice(new java.math.BigDecimal("25000")); cpu22.setSocket("LGA1700"); cpu22.setTdp(150); cpu22.setRamTypeSupport("DDR4, DDR5"); cpu22.setCores(10); componentService.saveComponent(cpu22);
            Cpu cpu23 = new Cpu(); cpu23.setName("Ryzen 7 5800X3D"); cpu23.setBrand("AMD"); cpu23.setPrice(new java.math.BigDecimal("33000")); cpu23.setSocket("AM4"); cpu23.setTdp(105); cpu23.setRamTypeSupport("DDR4"); cpu23.setCores(8); componentService.saveComponent(cpu23);
            Cpu cpu24 = new Cpu(); cpu24.setName("Core i9-12900KS"); cpu24.setBrand("Intel"); cpu24.setPrice(new java.math.BigDecimal("55000")); cpu24.setSocket("LGA1700"); cpu24.setTdp(241); cpu24.setRamTypeSupport("DDR4, DDR5"); cpu24.setCores(16); componentService.saveComponent(cpu24);

            // ================= МАТЕРИНСКИЕ ПЛАТЫ (доп) =================
            Motherboard mb1 = new Motherboard(); mb1.setName("PRO H610M-E"); mb1.setBrand("MSI"); mb1.setPrice(new java.math.BigDecimal("7500")); mb1.setSocket("LGA1700"); mb1.setRamType("DDR4"); mb1.setChipset("H610"); mb1.setFormFactor("Micro-ATX"); componentService.saveComponent(mb1);
            Motherboard mb2 = new Motherboard(); mb2.setName("Z790 GAMING PLUS WIFI"); mb2.setBrand("MSI"); mb2.setPrice(new java.math.BigDecimal("25000")); mb2.setSocket("LGA1700"); mb2.setRamType("DDR5"); mb2.setChipset("Z790"); mb2.setFormFactor("ATX"); componentService.saveComponent(mb2);
            Motherboard mb3 = new Motherboard(); mb3.setName("B550 AORUS ELITE V2"); mb3.setBrand("GIGABYTE"); mb3.setPrice(new java.math.BigDecimal("13000")); mb3.setSocket("AM4"); mb3.setRamType("DDR4"); mb3.setChipset("B550"); mb3.setFormFactor("ATX"); componentService.saveComponent(mb3);
            Motherboard mb4 = new Motherboard(); mb4.setName("B650M DS3H"); mb4.setBrand("GIGABYTE"); mb4.setPrice(new java.math.BigDecimal("16000")); mb4.setSocket("AM5"); mb4.setRamType("DDR5"); mb4.setChipset("B650"); mb4.setFormFactor("Micro-ATX"); componentService.saveComponent(mb4);
            Motherboard mb5 = new Motherboard(); mb5.setName("MAG B760 TOMAHAWK WIFI"); mb5.setBrand("MSI"); mb5.setPrice(new java.math.BigDecimal("21000")); mb5.setSocket("LGA1700"); mb5.setRamType("DDR5"); mb5.setChipset("B760"); mb5.setFormFactor("ATX"); componentService.saveComponent(mb5);
            Motherboard mb6 = new Motherboard(); mb6.setName("TUF GAMING B760-PLUS WIFI"); mb6.setBrand("ASUS"); mb6.setPrice(new java.math.BigDecimal("19000")); mb6.setSocket("LGA1700"); mb6.setRamType("DDR5"); mb6.setChipset("B760"); mb6.setFormFactor("ATX"); componentService.saveComponent(mb6);
            Motherboard mb7 = new Motherboard(); mb7.setName("PRIME H610M-K D4"); mb7.setBrand("ASUS"); mb7.setPrice(new java.math.BigDecimal("6500")); mb7.setSocket("LGA1700"); mb7.setRamType("DDR4"); mb7.setChipset("H610"); mb7.setFormFactor("Micro-ATX"); componentService.saveComponent(mb7);
            Motherboard mb8 = new Motherboard(); mb8.setName("X670E AORUS MASTER"); mb8.setBrand("GIGABYTE"); mb8.setPrice(new java.math.BigDecimal("55000")); mb8.setSocket("AM5"); mb8.setRamType("DDR5"); mb8.setChipset("X670E"); mb8.setFormFactor("ATX"); componentService.saveComponent(mb8);
            Motherboard mb9 = new Motherboard(); mb9.setName("B650 AORUS ELITE AX"); mb9.setBrand("GIGABYTE"); mb9.setPrice(new java.math.BigDecimal("22000")); mb9.setSocket("AM5"); mb9.setRamType("DDR5"); mb9.setChipset("B650"); mb9.setFormFactor("ATX"); componentService.saveComponent(mb9);
            Motherboard mb10 = new Motherboard(); mb10.setName("ROG STRIX B550-F GAMING"); mb10.setBrand("ASUS"); mb10.setPrice(new java.math.BigDecimal("17000")); mb10.setSocket("AM4"); mb10.setRamType("DDR4"); mb10.setChipset("B550"); mb10.setFormFactor("ATX"); componentService.saveComponent(mb10);
            Motherboard mb11 = new Motherboard(); mb11.setName("Z690 AORUS ELITE AX"); mb11.setBrand("GIGABYTE"); mb11.setPrice(new java.math.BigDecimal("23000")); mb11.setSocket("LGA1700"); mb11.setRamType("DDR5"); mb11.setChipset("Z690"); mb11.setFormFactor("ATX"); componentService.saveComponent(mb11);
            Motherboard mb12 = new Motherboard(); mb12.setName("B760M DS3H AX"); mb12.setBrand("GIGABYTE"); mb12.setPrice(new java.math.BigDecimal("13000")); mb12.setSocket("LGA1700"); mb12.setRamType("DDR5"); mb12.setChipset("B760"); mb12.setFormFactor("Micro-ATX"); componentService.saveComponent(mb12);
            Motherboard mb13 = new Motherboard(); mb13.setName("ROG STRIX Z790-F GAMING"); mb13.setBrand("ASUS"); mb13.setPrice(new java.math.BigDecimal("42000")); mb13.setSocket("LGA1700"); mb13.setRamType("DDR5"); mb13.setChipset("Z790"); mb13.setFormFactor("ATX"); componentService.saveComponent(mb13);
            Motherboard mb14 = new Motherboard(); mb14.setName("MAG Z790 TOMAHAWK MAX WIFI"); mb14.setBrand("MSI"); mb14.setPrice(new java.math.BigDecimal("35000")); mb14.setSocket("LGA1700"); mb14.setRamType("DDR5"); mb14.setChipset("Z790"); mb14.setFormFactor("ATX"); componentService.saveComponent(mb14);
            Motherboard mb15 = new Motherboard(); mb15.setName("PRIME B450M-A II"); mb15.setBrand("ASUS"); mb15.setPrice(new java.math.BigDecimal("5500")); mb15.setSocket("AM4"); mb15.setRamType("DDR4"); mb15.setChipset("B450"); mb15.setFormFactor("Micro-ATX"); componentService.saveComponent(mb15);
            Motherboard mb16 = new Motherboard(); mb16.setName("B550M PRO-VDH WIFI"); mb16.setBrand("MSI"); mb16.setPrice(new java.math.BigDecimal("9000")); mb16.setSocket("AM4"); mb16.setRamType("DDR4"); mb16.setChipset("B550"); mb16.setFormFactor("Micro-ATX"); componentService.saveComponent(mb16);
            Motherboard mb17 = new Motherboard(); mb17.setName("X570 AORUS PRO"); mb17.setBrand("GIGABYTE"); mb17.setPrice(new java.math.BigDecimal("28000")); mb17.setSocket("AM4"); mb17.setRamType("DDR4"); mb17.setChipset("X570"); mb17.setFormFactor("ATX"); componentService.saveComponent(mb17);
            Motherboard mb18 = new Motherboard(); mb18.setName("B650E-F ROG STRIX GAMING"); mb18.setBrand("ASUS"); mb18.setPrice(new java.math.BigDecimal("30000")); mb18.setSocket("AM5"); mb18.setRamType("DDR5"); mb18.setChipset("B650E"); mb18.setFormFactor("ATX"); componentService.saveComponent(mb18);
            Motherboard mb19 = new Motherboard(); mb19.setName("X670E PRO RS"); mb19.setBrand("ASRock"); mb19.setPrice(new java.math.BigDecimal("35000")); mb19.setSocket("AM5"); mb19.setRamType("DDR5"); mb19.setChipset("X670E"); mb19.setFormFactor("ATX"); componentService.saveComponent(mb19);
            Motherboard mb20 = new Motherboard(); mb20.setName("B650M-A WIFI"); mb20.setBrand("MSI"); mb20.setPrice(new java.math.BigDecimal("14000")); mb20.setSocket("AM5"); mb20.setRamType("DDR5"); mb20.setChipset("B650"); mb20.setFormFactor("Micro-ATX"); componentService.saveComponent(mb20);
            Motherboard mb21 = new Motherboard(); mb21.setName("Z790 AORUS XTREME"); mb21.setBrand("GIGABYTE"); mb21.setPrice(new java.math.BigDecimal("75000")); mb21.setSocket("LGA1700"); mb21.setRamType("DDR5"); mb21.setChipset("Z790"); mb21.setFormFactor("ATX"); componentService.saveComponent(mb21);
            Motherboard mb22 = new Motherboard(); mb22.setName("TUF GAMING A520M-PLUS II"); mb22.setBrand("ASUS"); mb22.setPrice(new java.math.BigDecimal("6000")); mb22.setSocket("AM4"); mb22.setRamType("DDR4"); mb22.setChipset("A520"); mb22.setFormFactor("Micro-ATX"); componentService.saveComponent(mb22);

            // ================= ВИДЕОКАРТЫ (доп) =================
            Gpu gpu6 = new Gpu(); gpu6.setName("GeForce RTX 4090 GAMING OC"); gpu6.setBrand("GIGABYTE"); gpu6.setPrice(new java.math.BigDecimal("180000")); gpu6.setVideoMemory(24); gpu6.setRecommendedPower(1000); componentService.saveComponent(gpu6);
            Gpu gpu7 = new Gpu(); gpu7.setName("GeForce RTX 4060 VENTUS 2X"); gpu7.setBrand("MSI"); gpu7.setPrice(new java.math.BigDecimal("32000")); gpu7.setVideoMemory(8); gpu7.setRecommendedPower(550); componentService.saveComponent(gpu7);
            Gpu gpu8 = new Gpu(); gpu8.setName("Radeon RX 7600"); gpu8.setBrand("Sapphire"); gpu8.setPrice(new java.math.BigDecimal("27000")); gpu8.setVideoMemory(8); gpu8.setRecommendedPower(550); componentService.saveComponent(gpu8);
            Gpu gpu9 = new Gpu(); gpu9.setName("Radeon RX 7800 XT"); gpu9.setBrand("ASRock"); gpu9.setPrice(new java.math.BigDecimal("60000")); gpu9.setVideoMemory(16); gpu9.setRecommendedPower(700); componentService.saveComponent(gpu9);
            Gpu gpu10 = new Gpu(); gpu10.setName("GeForce RTX 3050"); gpu10.setBrand("Palit"); gpu10.setPrice(new java.math.BigDecimal("20000")); gpu10.setVideoMemory(8); gpu10.setRecommendedPower(450); componentService.saveComponent(gpu10);
            Gpu gpu11 = new Gpu(); gpu11.setName("Arc A750"); gpu11.setBrand("Intel"); gpu11.setPrice(new java.math.BigDecimal("25000")); gpu11.setVideoMemory(8); gpu11.setRecommendedPower(600); componentService.saveComponent(gpu11);
            Gpu gpu12 = new Gpu(); gpu12.setName("GeForce RTX 4070 Ti SUPER"); gpu12.setBrand("Palit"); gpu12.setPrice(new java.math.BigDecimal("85000")); gpu12.setVideoMemory(16); gpu12.setRecommendedPower(750); componentService.saveComponent(gpu12);
            Gpu gpu13 = new Gpu(); gpu13.setName("GeForce RTX 4080 SUPER GAMING OC"); gpu13.setBrand("GIGABYTE"); gpu13.setPrice(new java.math.BigDecimal("110000")); gpu13.setVideoMemory(16); gpu13.setRecommendedPower(750); componentService.saveComponent(gpu13);
            Gpu gpu14 = new Gpu(); gpu14.setName("GeForce RTX 4070 VENTUS 3X"); gpu14.setBrand("MSI"); gpu14.setPrice(new java.math.BigDecimal("62000")); gpu14.setVideoMemory(12); gpu14.setRecommendedPower(650); componentService.saveComponent(gpu14);
            Gpu gpu15 = new Gpu(); gpu15.setName("GeForce RTX 4060 Ti GAMING X"); gpu15.setBrand("MSI"); gpu15.setPrice(new java.math.BigDecimal("42000")); gpu15.setVideoMemory(16); gpu15.setRecommendedPower(550); componentService.saveComponent(gpu15);
            Gpu gpu16 = new Gpu(); gpu16.setName("Radeon RX 7900 GRE"); gpu16.setBrand("Sapphire"); gpu16.setPrice(new java.math.BigDecimal("68000")); gpu16.setVideoMemory(16); gpu16.setRecommendedPower(700); componentService.saveComponent(gpu16);
            Gpu gpu17 = new Gpu(); gpu17.setName("Radeon RX 7700 XT"); gpu17.setBrand("PowerColor"); gpu17.setPrice(new java.math.BigDecimal("48000")); gpu17.setVideoMemory(12); gpu17.setRecommendedPower(650); componentService.saveComponent(gpu17);
            Gpu gpu18 = new Gpu(); gpu18.setName("Radeon RX 6600"); gpu18.setBrand("ASRock"); gpu18.setPrice(new java.math.BigDecimal("22000")); gpu18.setVideoMemory(8); gpu18.setRecommendedPower(500); componentService.saveComponent(gpu18);
            Gpu gpu19 = new Gpu(); gpu19.setName("GeForce RTX 3090 Ti SUPRIM X"); gpu19.setBrand("MSI"); gpu19.setPrice(new java.math.BigDecimal("150000")); gpu19.setVideoMemory(24); gpu19.setRecommendedPower(850); componentService.saveComponent(gpu19);
            Gpu gpu20 = new Gpu(); gpu20.setName("Radeon RX 6950 XT"); gpu20.setBrand("XFX"); gpu20.setPrice(new java.math.BigDecimal("75000")); gpu20.setVideoMemory(16); gpu20.setRecommendedPower(850); componentService.saveComponent(gpu20);
            Gpu gpu21 = new Gpu(); gpu21.setName("Arc A770 Phantom Gaming"); gpu21.setBrand("ASRock"); gpu21.setPrice(new java.math.BigDecimal("32000")); gpu21.setVideoMemory(16); gpu21.setRecommendedPower(650); componentService.saveComponent(gpu21);
            Gpu gpu22 = new Gpu(); gpu22.setName("GeForce GTX 1660 SUPER"); gpu22.setBrand("ASUS"); gpu22.setPrice(new java.math.BigDecimal("18000")); gpu22.setVideoMemory(6); gpu22.setRecommendedPower(450); componentService.saveComponent(gpu22);
            Gpu gpu23 = new Gpu(); gpu23.setName("Radeon RX 7600 XT"); gpu23.setBrand("GIGABYTE"); gpu23.setPrice(new java.math.BigDecimal("35000")); gpu23.setVideoMemory(16); gpu23.setRecommendedPower(600); componentService.saveComponent(gpu23);
            Gpu gpu24 = new Gpu(); gpu24.setName("GeForce RTX 4090 SUPRIM LIQUID X"); gpu24.setBrand("MSI"); gpu24.setPrice(new java.math.BigDecimal("210000")); gpu24.setVideoMemory(24); gpu24.setRecommendedPower(1000); componentService.saveComponent(gpu24);

            // ================= ОПЕРАТИВНАЯ ПАМЯТЬ (доп) =================
            Ram ram5 = new Ram(); ram5.setName("Vengeance LPX Black"); ram5.setBrand("Corsair"); ram5.setPrice(new java.math.BigDecimal("4200")); ram5.setRamType("DDR4"); ram5.setCapacityGb(16); ram5.setFrequencyMhz(3200); componentService.saveComponent(ram5);
            Ram ram6 = new Ram(); ram6.setName("FURY Renegade Black"); ram6.setBrand("Kingston"); ram6.setPrice(new java.math.BigDecimal("9500")); ram6.setRamType("DDR4"); ram6.setCapacityGb(32); ram6.setFrequencyMhz(4000); componentService.saveComponent(ram6);
            Ram ram7 = new Ram(); ram7.setName("Trident Z5 Neo RGB"); ram7.setBrand("G.Skill"); ram7.setPrice(new java.math.BigDecimal("13000")); ram7.setRamType("DDR5"); ram7.setCapacityGb(32); ram7.setFrequencyMhz(6000); componentService.saveComponent(ram7);
            Ram ram8 = new Ram(); ram8.setName("Dominator Platinum RGB"); ram8.setBrand("Corsair"); ram8.setPrice(new java.math.BigDecimal("28000")); ram8.setRamType("DDR5"); ram8.setCapacityGb(64); ram8.setFrequencyMhz(6600); componentService.saveComponent(ram8);
            Ram ram9 = new Ram(); ram9.setName("Fury Impact"); ram9.setBrand("Kingston"); ram9.setPrice(new java.math.BigDecimal("3800")); ram9.setRamType("DDR4"); ram9.setCapacityGb(8); ram9.setFrequencyMhz(3200); componentService.saveComponent(ram9);
            Ram ram10 = new Ram(); ram10.setName("Aegis"); ram10.setBrand("G.Skill"); ram10.setPrice(new java.math.BigDecimal("3500")); ram10.setRamType("DDR4"); ram10.setCapacityGb(16); ram10.setFrequencyMhz(3000); componentService.saveComponent(ram10);
            Ram ram11 = new Ram(); ram11.setName("FURY Beast RGB"); ram11.setBrand("Kingston"); ram11.setPrice(new java.math.BigDecimal("5000")); ram11.setRamType("DDR4"); ram11.setCapacityGb(16); ram11.setFrequencyMhz(3600); componentService.saveComponent(ram11);
            Ram ram12 = new Ram(); ram12.setName("Vengeance RGB PRO"); ram12.setBrand("Corsair"); ram12.setPrice(new java.math.BigDecimal("8000")); ram12.setRamType("DDR4"); ram12.setCapacityGb(32); ram12.setFrequencyMhz(3600); componentService.saveComponent(ram12);
            Ram ram13 = new Ram(); ram13.setName("Trident Z Neo"); ram13.setBrand("G.Skill"); ram13.setPrice(new java.math.BigDecimal("12000")); ram13.setRamType("DDR4"); ram13.setCapacityGb(32); ram13.setFrequencyMhz(4000); componentService.saveComponent(ram13);
            Ram ram14 = new Ram(); ram14.setName("FURY Beast"); ram14.setBrand("Kingston"); ram14.setPrice(new java.math.BigDecimal("10000")); ram14.setRamType("DDR5"); ram14.setCapacityGb(32); ram14.setFrequencyMhz(5600); componentService.saveComponent(ram14);
            Ram ram15 = new Ram(); ram15.setName("Vengeance Black"); ram15.setBrand("Corsair"); ram15.setPrice(new java.math.BigDecimal("14000")); ram15.setRamType("DDR5"); ram15.setCapacityGb(32); ram15.setFrequencyMhz(6000); componentService.saveComponent(ram15);
            Ram ram16 = new Ram(); ram16.setName("Trident Z5 RGB"); ram16.setBrand("G.Skill"); ram16.setPrice(new java.math.BigDecimal("35000")); ram16.setRamType("DDR5"); ram16.setCapacityGb(96); ram16.setFrequencyMhz(6800); componentService.saveComponent(ram16);
            Ram ram17 = new Ram(); ram17.setName("Ripjaws S5"); ram17.setBrand("G.Skill"); ram17.setPrice(new java.math.BigDecimal("9000")); ram17.setRamType("DDR5"); ram17.setCapacityGb(32); ram17.setFrequencyMhz(5600); componentService.saveComponent(ram17);
            Ram ram18 = new Ram(); ram18.setName("Ballistix"); ram18.setBrand("Crucial"); ram18.setPrice(new java.math.BigDecimal("4000")); ram18.setRamType("DDR4"); ram18.setCapacityGb(16); ram18.setFrequencyMhz(3200); componentService.saveComponent(ram18);
            Ram ram19 = new Ram(); ram19.setName("FURY Renegade Silver"); ram19.setBrand("Kingston"); ram19.setPrice(new java.math.BigDecimal("15000")); ram19.setRamType("DDR5"); ram19.setCapacityGb(32); ram19.setFrequencyMhz(7200); componentService.saveComponent(ram19);
            Ram ram20 = new Ram(); ram20.setName("TeamGroup T-Force Vulcan"); ram20.setBrand("TeamGroup"); ram20.setPrice(new java.math.BigDecimal("8500")); ram20.setRamType("DDR5"); ram20.setCapacityGb(32); ram20.setFrequencyMhz(5600); componentService.saveComponent(ram20);
            Ram ram21 = new Ram(); ram21.setName("Vengeance LPX Black"); ram21.setBrand("Corsair"); ram21.setPrice(new java.math.BigDecimal("4500")); ram21.setRamType("DDR4"); ram21.setCapacityGb(8); ram21.setFrequencyMhz(3200); componentService.saveComponent(ram21);
            Ram ram22 = new Ram(); ram22.setName("G.Skill Flare X5"); ram22.setBrand("G.Skill"); ram22.setPrice(new java.math.BigDecimal("11000")); ram22.setRamType("DDR5"); ram22.setCapacityGb(32); ram22.setFrequencyMhz(6000); componentService.saveComponent(ram22);

            // ================= ОХЛАЖДЕНИЕ (доп) =================
            Cooler cooler5 = new Cooler(); cooler5.setName("Pure Rock 2"); cooler5.setBrand("be quiet!"); cooler5.setPrice(new java.math.BigDecimal("3500")); cooler5.setCoolingType("ВОЗДУШНОЕ"); cooler5.setMaxTdp(150); componentService.saveComponent(cooler5);
            Cooler cooler6 = new Cooler(); cooler6.setName("Dark Rock Pro 5"); cooler6.setBrand("be quiet!"); cooler6.setPrice(new java.math.BigDecimal("9500")); cooler6.setCoolingType("ВОЗДУШНОЕ"); cooler6.setMaxTdp(270); componentService.saveComponent(cooler6);
            Cooler cooler7 = new Cooler(); cooler7.setName("NH-D15"); cooler7.setBrand("Noctua"); cooler7.setPrice(new java.math.BigDecimal("10000")); cooler7.setCoolingType("ВОЗДУШНОЕ"); cooler7.setMaxTdp(250); componentService.saveComponent(cooler7);
            Cooler cooler8 = new Cooler(); cooler8.setName("iCUE H150i ELITE CAPELLIX XT"); cooler8.setBrand("Corsair"); cooler8.setPrice(new java.math.BigDecimal("18000")); cooler8.setCoolingType("ВОДЯНОЕ"); cooler8.setMaxTdp(350); componentService.saveComponent(cooler8);
            Cooler cooler9 = new Cooler(); cooler9.setName("Kraken X63"); cooler9.setBrand("NZXT"); cooler9.setPrice(new java.math.BigDecimal("14000")); cooler9.setCoolingType("ВОДЯНОЕ"); cooler9.setMaxTdp(320); componentService.saveComponent(cooler9);
            Cooler cooler10 = new Cooler(); cooler10.setName("AG400"); cooler10.setBrand("DeepCool"); cooler10.setPrice(new java.math.BigDecimal("1800")); cooler10.setCoolingType("ВОЗДУШНОЕ"); cooler10.setMaxTdp(220); componentService.saveComponent(cooler10);
            Cooler cooler11 = new Cooler(); cooler11.setName("Hyper 212 Black Edition"); cooler11.setBrand("Cooler Master"); cooler11.setPrice(new java.math.BigDecimal("3500")); cooler11.setCoolingType("ВОЗДУШНОЕ"); cooler11.setMaxTdp(180); componentService.saveComponent(cooler11);
            Cooler cooler12 = new Cooler(); cooler12.setName("NH-U12S Redux"); cooler12.setBrand("Noctua"); cooler12.setPrice(new java.math.BigDecimal("5500")); cooler12.setCoolingType("ВОЗДУШНОЕ"); cooler12.setMaxTdp(200); componentService.saveComponent(cooler12);
            Cooler cooler13 = new Cooler(); cooler13.setName("Shadow Rock 3"); cooler13.setBrand("be quiet!"); cooler13.setPrice(new java.math.BigDecimal("5000")); cooler13.setCoolingType("ВОЗДУШНОЕ"); cooler13.setMaxTdp(190); componentService.saveComponent(cooler13);
            Cooler cooler14 = new Cooler(); cooler14.setName("Freezer 34 eSports DUO"); cooler14.setBrand("Arctic"); cooler14.setPrice(new java.math.BigDecimal("4000")); cooler14.setCoolingType("ВОЗДУШНОЕ"); cooler14.setMaxTdp(210); componentService.saveComponent(cooler14);
            Cooler cooler15 = new Cooler(); cooler15.setName("MasterLiquid ML360R RGB"); cooler15.setBrand("Cooler Master"); cooler15.setPrice(new java.math.BigDecimal("14000")); cooler15.setCoolingType("ВОДЯНОЕ"); cooler15.setMaxTdp(350); componentService.saveComponent(cooler15);
            Cooler cooler16 = new Cooler(); cooler16.setName("Pure Loop 2 FX 280mm"); cooler16.setBrand("be quiet!"); cooler16.setPrice(new java.math.BigDecimal("11000")); cooler16.setCoolingType("ВОДЯНОЕ"); cooler16.setMaxTdp(300); componentService.saveComponent(cooler16);
            Cooler cooler17 = new Cooler(); cooler17.setName("LT720"); cooler17.setBrand("DeepCool"); cooler17.setPrice(new java.math.BigDecimal("13000")); cooler17.setCoolingType("ВОДЯНОЕ"); cooler17.setMaxTdp(350); componentService.saveComponent(cooler17);
            Cooler cooler18 = new Cooler(); cooler18.setName("SE-224-XT Black"); cooler18.setBrand("ID-Cooling"); cooler18.setPrice(new java.math.BigDecimal("2200")); cooler18.setCoolingType("ВОЗДУШНОЕ"); cooler18.setMaxTdp(180); componentService.saveComponent(cooler18);
            Cooler cooler19 = new Cooler(); cooler19.setName("Freezer 36 A-RGB"); cooler19.setBrand("Arctic"); cooler19.setPrice(new java.math.BigDecimal("3000")); cooler19.setCoolingType("ВОЗДУШНОЕ"); cooler19.setMaxTdp(200); componentService.saveComponent(cooler19);
            Cooler cooler20 = new Cooler(); cooler20.setName("Kraken Elite 360 RGB"); cooler20.setBrand("NZXT"); cooler20.setPrice(new java.math.BigDecimal("22000")); cooler20.setCoolingType("ВОДЯНОЕ"); cooler20.setMaxTdp(380); componentService.saveComponent(cooler20);
            Cooler cooler21 = new Cooler(); cooler21.setName("AK620 Digital"); cooler21.setBrand("DeepCool"); cooler21.setPrice(new java.math.BigDecimal("6500")); cooler21.setCoolingType("ВОЗДУШНОЕ"); cooler21.setMaxTdp(260); componentService.saveComponent(cooler21);
            Cooler cooler22 = new Cooler(); cooler22.setName("NH-L9i-17xx"); cooler22.setBrand("Noctua"); cooler22.setPrice(new java.math.BigDecimal("4500")); cooler22.setCoolingType("ВОЗДУШНОЕ"); cooler22.setMaxTdp(95); componentService.saveComponent(cooler22);

            // ================= НАКОПИТЕЛИ (доп) =================
            Storage st5 = new Storage(); st5.setName("990 PRO"); st5.setBrand("Samsung"); st5.setPrice(new java.math.BigDecimal("18000")); st5.setStorageType("SSD M.2"); st5.setCapacityGb(2000); componentService.saveComponent(st5);
            Storage st6 = new Storage(); st6.setName("NV2"); st6.setBrand("Kingston"); st6.setPrice(new java.math.BigDecimal("3500")); st6.setStorageType("SSD M.2"); st6.setCapacityGb(500); componentService.saveComponent(st6);
            Storage st7 = new Storage(); st7.setName("870 EVO"); st7.setBrand("Samsung"); st7.setPrice(new java.math.BigDecimal("6000")); st7.setStorageType("SSD SATA"); st7.setCapacityGb(1000); componentService.saveComponent(st7);
            Storage st8 = new Storage(); st8.setName("FireCuda 530"); st8.setBrand("Seagate"); st8.setPrice(new java.math.BigDecimal("20000")); st8.setStorageType("SSD M.2"); st8.setCapacityGb(2000); componentService.saveComponent(st8);
            Storage st9 = new Storage(); st9.setName("WD Black SN850X"); st9.setBrand("Western Digital"); st9.setPrice(new java.math.BigDecimal("15000")); st9.setStorageType("SSD M.2"); st9.setCapacityGb(2000); componentService.saveComponent(st9);
            Storage st10 = new Storage(); st10.setName("IronWolf"); st10.setBrand("Seagate"); st10.setPrice(new java.math.BigDecimal("8000")); st10.setStorageType("HDD"); st10.setCapacityGb(4000); componentService.saveComponent(st10);
            Storage st11 = new Storage(); st11.setName("MP600 PRO NH"); st11.setBrand("Corsair"); st11.setPrice(new java.math.BigDecimal("12000")); st11.setStorageType("SSD M.2"); st11.setCapacityGb(2000); componentService.saveComponent(st11);
            Storage st12 = new Storage(); st12.setName("970 EVO Plus"); st12.setBrand("Samsung"); st12.setPrice(new java.math.BigDecimal("7000")); st12.setStorageType("SSD M.2"); st12.setCapacityGb(1000); componentService.saveComponent(st12);
            Storage st13 = new Storage(); st13.setName("A400"); st13.setBrand("Kingston"); st13.setPrice(new java.math.BigDecimal("2500")); st13.setStorageType("SSD SATA"); st13.setCapacityGb(480); componentService.saveComponent(st13);
            Storage st14 = new Storage(); st14.setName("WD Red Plus"); st14.setBrand("Western Digital"); st14.setPrice(new java.math.BigDecimal("10000")); st14.setStorageType("HDD"); st14.setCapacityGb(4000); componentService.saveComponent(st14);
            Storage st15 = new Storage(); st15.setName("P3 Plus"); st15.setBrand("Crucial"); st15.setPrice(new java.math.BigDecimal("5000")); st15.setStorageType("SSD M.2"); st15.setCapacityGb(1000); componentService.saveComponent(st15);
            Storage st16 = new Storage(); st16.setName("T500"); st16.setBrand("Crucial"); st16.setPrice(new java.math.BigDecimal("13000")); st16.setStorageType("SSD M.2"); st16.setCapacityGb(2000); componentService.saveComponent(st16);
            Storage st17 = new Storage(); st17.setName("Exceria Pro"); st17.setBrand("Kioxia"); st17.setPrice(new java.math.BigDecimal("11000")); st17.setStorageType("SSD M.2"); st17.setCapacityGb(2000); componentService.saveComponent(st17);
            Storage st18 = new Storage(); st18.setName("SkyHawk"); st18.setBrand("Seagate"); st18.setPrice(new java.math.BigDecimal("7000")); st18.setStorageType("HDD"); st18.setCapacityGb(2000); componentService.saveComponent(st18);
            Storage st19 = new Storage(); st19.setName("WD Green SN350"); st19.setBrand("Western Digital"); st19.setPrice(new java.math.BigDecimal("3000")); st19.setStorageType("SSD M.2"); st19.setCapacityGb(480); componentService.saveComponent(st19);
            Storage st20 = new Storage(); st20.setName("980"); st20.setBrand("Samsung"); st20.setPrice(new java.math.BigDecimal("5500")); st20.setStorageType("SSD M.2"); st20.setCapacityGb(500); componentService.saveComponent(st20);
            Storage st21 = new Storage(); st21.setName("P5 Plus"); st21.setBrand("Crucial"); st21.setPrice(new java.math.BigDecimal("8500")); st21.setStorageType("SSD M.2"); st21.setCapacityGb(1000); componentService.saveComponent(st21);
            Storage st22 = new Storage(); st22.setName("WD Blue SA510"); st22.setBrand("Western Digital"); st22.setPrice(new java.math.BigDecimal("3500")); st22.setStorageType("SSD SATA"); st22.setCapacityGb(500); componentService.saveComponent(st22);

            // ================= БЛОКИ ПИТАНИЯ (доп) =================
            PowerSupply psu5 = new PowerSupply(); psu5.setName("Corsair CX550"); psu5.setBrand("Corsair"); psu5.setPrice(new java.math.BigDecimal("4500")); psu5.setWattage(550); psu5.setCertificate("80+ Bronze"); componentService.saveComponent(psu5);
            PowerSupply psu6 = new PowerSupply(); psu6.setName("RM850x SHIFT"); psu6.setBrand("Corsair"); psu6.setPrice(new java.math.BigDecimal("16000")); psu6.setWattage(850); psu6.setCertificate("80+ Gold"); componentService.saveComponent(psu6);
            PowerSupply psu7 = new PowerSupply(); psu7.setName("Toughpower GF3 750W"); psu7.setBrand("Thermaltake"); psu7.setPrice(new java.math.BigDecimal("12000")); psu7.setWattage(750); psu7.setCertificate("80+ Gold"); componentService.saveComponent(psu7);
            PowerSupply psu8 = new PowerSupply(); psu8.setName("Straight Power 12 1200W"); psu8.setBrand("be quiet!"); psu8.setPrice(new java.math.BigDecimal("32000")); psu8.setWattage(1200); psu8.setCertificate("80+ Platinum"); componentService.saveComponent(psu8);
            PowerSupply psu9 = new PowerSupply(); psu9.setName("V750"); psu9.setBrand("Cooler Master"); psu9.setPrice(new java.math.BigDecimal("8000")); psu9.setWattage(750); psu9.setCertificate("80+ Gold"); componentService.saveComponent(psu9);
            PowerSupply psu10 = new PowerSupply(); psu10.setName("ROG Thor 1600W"); psu10.setBrand("ASUS"); psu10.setPrice(new java.math.BigDecimal("55000")); psu10.setWattage(1600); psu10.setCertificate("80+ Titanium"); componentService.saveComponent(psu10);
            PowerSupply psu11 = new PowerSupply(); psu11.setName("Pure Power 12 M 750W"); psu11.setBrand("be quiet!"); psu11.setPrice(new java.math.BigDecimal("10500")); psu11.setWattage(750); psu11.setCertificate("80+ Gold"); componentService.saveComponent(psu11);
            PowerSupply psu12 = new PowerSupply(); psu12.setName("SF750"); psu12.setBrand("Corsair"); psu12.setPrice(new java.math.BigDecimal("16000")); psu12.setWattage(750); psu12.setCertificate("80+ Platinum"); componentService.saveComponent(psu12);
            PowerSupply psu13 = new PowerSupply(); psu13.setName("Toughpower GF A3 1050W"); psu13.setBrand("Thermaltake"); psu13.setPrice(new java.math.BigDecimal("18000")); psu13.setWattage(1050); psu13.setCertificate("80+ Gold"); componentService.saveComponent(psu13);
            PowerSupply psu14 = new PowerSupply(); psu14.setName("MWE 500 White V2"); psu14.setBrand("Cooler Master"); psu14.setPrice(new java.math.BigDecimal("3500")); psu14.setWattage(500); psu14.setCertificate("80+ White"); componentService.saveComponent(psu14);
            PowerSupply psu15 = new PowerSupply(); psu15.setName("Focus GX-850"); psu15.setBrand("Seasonic"); psu15.setPrice(new java.math.BigDecimal("13000")); psu15.setWattage(850); psu15.setCertificate("80+ Gold"); componentService.saveComponent(psu15);
            PowerSupply psu16 = new PowerSupply(); psu16.setName("Prime TX-1000"); psu16.setBrand("Seasonic"); psu16.setPrice(new java.math.BigDecimal("35000")); psu16.setWattage(1000); psu16.setCertificate("80+ Titanium"); componentService.saveComponent(psu16);
            PowerSupply psu17 = new PowerSupply(); psu17.setName("RM1000e"); psu17.setBrand("Corsair"); psu17.setPrice(new java.math.BigDecimal("18000")); psu17.setWattage(1000); psu17.setCertificate("80+ Gold"); componentService.saveComponent(psu17);
            PowerSupply psu18 = new PowerSupply(); psu18.setName("V850 SFX Gold"); psu18.setBrand("Cooler Master"); psu18.setPrice(new java.math.BigDecimal("15000")); psu18.setWattage(850); psu18.setCertificate("80+ Gold"); componentService.saveComponent(psu18);
            PowerSupply psu19 = new PowerSupply(); psu19.setName("A850GF"); psu19.setBrand("MSI"); psu19.setPrice(new java.math.BigDecimal("11000")); psu19.setWattage(850); psu19.setCertificate("80+ Gold"); componentService.saveComponent(psu19);
            PowerSupply psu20 = new PowerSupply(); psu20.setName("TUF Gaming 750W"); psu20.setBrand("ASUS"); psu20.setPrice(new java.math.BigDecimal("10000")); psu20.setWattage(750); psu20.setCertificate("80+ Bronze"); componentService.saveComponent(psu20);
            PowerSupply psu21 = new PowerSupply(); psu21.setName("MWE Gold 850 V2"); psu21.setBrand("Cooler Master"); psu21.setPrice(new java.math.BigDecimal("12000")); psu21.setWattage(850); psu21.setCertificate("80+ Gold"); componentService.saveComponent(psu21);
            PowerSupply psu22 = new PowerSupply(); psu22.setName("Silentstorm Cool Zero 850W"); psu22.setBrand("XPG"); psu22.setPrice(new java.math.BigDecimal("13000")); psu22.setWattage(850); psu22.setCertificate("80+ Gold"); componentService.saveComponent(psu22);

            // ================= КОРПУСА (доп) =================
            PcCase c4 = new PcCase(); c4.setName("4000D Airflow"); c4.setBrand("Corsair"); c4.setPrice(new java.math.BigDecimal("9000")); c4.setFormFactor("ATX"); c4.setMaxGpuLengthMm(360); componentService.saveComponent(c4);
            PcCase c5 = new PcCase(); c5.setName("Pure Base 600"); c5.setBrand("be quiet!"); c5.setPrice(new java.math.BigDecimal("8000")); c5.setFormFactor("ATX"); c5.setMaxGpuLengthMm(425); componentService.saveComponent(c5);
            PcCase c6 = new PcCase(); c6.setName("Lancool 216"); c6.setBrand("Lian Li"); c6.setPrice(new java.math.BigDecimal("7500")); c6.setFormFactor("ATX"); c6.setMaxGpuLengthMm(392); componentService.saveComponent(c6);
            PcCase c7 = new PcCase(); c7.setName("O11 Dynamic Mini"); c7.setBrand("Lian Li"); c7.setPrice(new java.math.BigDecimal("11000")); c7.setFormFactor("Mini-Tower"); c7.setMaxGpuLengthMm(395); componentService.saveComponent(c7);
            PcCase c8 = new PcCase(); c8.setName("Torrent Compact"); c8.setBrand("Fractal Design"); c8.setPrice(new java.math.BigDecimal("12000")); c8.setFormFactor("ATX"); c8.setMaxGpuLengthMm(330); componentService.saveComponent(c8);
            PcCase c9 = new PcCase(); c9.setName("Pop Air"); c9.setBrand("Fractal Design"); c9.setPrice(new java.math.BigDecimal("6500")); c9.setFormFactor("ATX"); c9.setMaxGpuLengthMm(405); componentService.saveComponent(c9);
            PcCase c10 = new PcCase(); c10.setName("MB520"); c10.setBrand("Cooler Master"); c10.setPrice(new java.math.BigDecimal("6000")); c10.setFormFactor("ATX"); c10.setMaxGpuLengthMm(410); componentService.saveComponent(c10);
            PcCase c11 = new PcCase(); c11.setName("H7 Flow"); c11.setBrand("NZXT"); c11.setPrice(new java.math.BigDecimal("13000")); c11.setFormFactor("ATX"); c11.setMaxGpuLengthMm(400); componentService.saveComponent(c11);
            PcCase c12 = new PcCase(); c12.setName("H9 Elite"); c12.setBrand("NZXT"); c12.setPrice(new java.math.BigDecimal("20000")); c12.setFormFactor("ATX"); c12.setMaxGpuLengthMm(435); componentService.saveComponent(c12);
            PcCase c13 = new PcCase(); c13.setName("5000D Airflow"); c13.setBrand("Corsair"); c13.setPrice(new java.math.BigDecimal("15000")); c13.setFormFactor("ATX"); c13.setMaxGpuLengthMm(420); componentService.saveComponent(c13);
            PcCase c14 = new PcCase(); c14.setName("Meshify 2"); c14.setBrand("Fractal Design"); c14.setPrice(new java.math.BigDecimal("14000")); c14.setFormFactor("ATX"); c14.setMaxGpuLengthMm(491); componentService.saveComponent(c14);
            PcCase c15 = new PcCase(); c15.setName("Define 7 Compact"); c15.setBrand("Fractal Design"); c15.setPrice(new java.math.BigDecimal("10000")); c15.setFormFactor("ATX"); c15.setMaxGpuLengthMm(360); componentService.saveComponent(c15);
            PcCase c16 = new PcCase(); c16.setName("CH370"); c16.setBrand("DeepCool"); c16.setPrice(new java.math.BigDecimal("4500")); c16.setFormFactor("Micro-ATX"); c16.setMaxGpuLengthMm(320); componentService.saveComponent(c16);
            PcCase c17 = new PcCase(); c17.setName("Silent Base 802"); c17.setBrand("be quiet!"); c17.setPrice(new java.math.BigDecimal("15000")); c17.setFormFactor("ATX"); c17.setMaxGpuLengthMm(432); componentService.saveComponent(c17);
            PcCase c18 = new PcCase(); c18.setName("MasterBox TD500 Mesh V2"); c18.setBrand("Cooler Master"); c18.setPrice(new java.math.BigDecimal("8500")); c18.setFormFactor("ATX"); c18.setMaxGpuLengthMm(410); componentService.saveComponent(c18);
            PcCase c19 = new PcCase(); c19.setName("Ncore 100 MAX"); c19.setBrand("Cooler Master"); c19.setPrice(new java.math.BigDecimal("12000")); c19.setFormFactor("Mini-ITX"); c19.setMaxGpuLengthMm(357); componentService.saveComponent(c19);
            PcCase c20 = new PcCase(); c20.setName("Terra"); c20.setBrand("Fractal Design"); c20.setPrice(new java.math.BigDecimal("16000")); c20.setFormFactor("Mini-ITX"); c20.setMaxGpuLengthMm(322); componentService.saveComponent(c20);
            PcCase c21 = new PcCase(); c21.setName("O11 Vision"); c21.setBrand("Lian Li"); c21.setPrice(new java.math.BigDecimal("16000")); c21.setFormFactor("ATX"); c21.setMaxGpuLengthMm(455); componentService.saveComponent(c21);
            PcCase c22 = new PcCase(); c22.setName("MAG Forge 112A"); c22.setBrand("MSI"); c22.setPrice(new java.math.BigDecimal("5500")); c22.setFormFactor("ATX"); c22.setMaxGpuLengthMm(330); componentService.saveComponent(c22);
        }
    }
}